# Generated by Django 5.2.1 on 2025-07-28 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('idaula', models.AutoField(db_column='idAula', primary_key=True, serialize=False, verbose_name='ID Aula')),
                ('capacidad', models.CharField(max_length=20, verbose_name='Capacidad')),
                ('aire', models.IntegerField(verbose_name='Aire Acondicionado')),
                ('videobeam', models.IntegerField(verbose_name='Video Beam')),
                ('pizarra', models.IntegerField(verbose_name='Pizarra')),
                ('ubicacion', models.CharField(max_length=30, verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'db_table': 'aula',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('idcarrera', models.AutoField(db_column='idCarrera', primary_key=True, serialize=False, verbose_name='ID Carrera')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre de Carrera')),
                ('numero_semestre', models.IntegerField(verbose_name='Número de Semestres')),
                ('modalidad', models.CharField(max_length=15, verbose_name='Modalidad')),
                ('mencion', models.CharField(max_length=40, verbose_name='Mención')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'db_table': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('idestudiante', models.AutoField(db_column='idEstudiante', primary_key=True, serialize=False, verbose_name='ID Estudiante')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='estudiantes/', verbose_name='Foto')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('direccion', models.CharField(max_length=80, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('fecha_ing', models.DateField(verbose_name='Fecha de Ingreso')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('idprofesor', models.AutoField(db_column='idProfesor', primary_key=True, serialize=False, verbose_name='ID Profesor')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='profesores/', verbose_name='Foto')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('direccion', models.CharField(max_length=80, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('especialidad', models.CharField(max_length=80, verbose_name='Especialidad')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'profesor',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('idmateria', models.AutoField(db_column='idMateria', primary_key=True, serialize=False, verbose_name='ID Materia')),
                ('nombre_materia', models.CharField(max_length=40, verbose_name='Nombre de Materia')),
                ('unidades_creditos', models.IntegerField(verbose_name='Unidades de Créditos')),
                ('modalidad', models.CharField(max_length=20, verbose_name='Modalidad')),
                ('idcarrera', models.ForeignKey(db_column='idCarrera', on_delete=django.db.models.deletion.CASCADE, to='appu.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'materia',
            },
        ),
        migrations.CreateModel(
            name='CarreraEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcarrera', models.ForeignKey(db_column='idCarrera', on_delete=django.db.models.deletion.CASCADE, to='appu.carrera', verbose_name='Carrera')),
                ('idestudiante', models.ForeignKey(db_column='idEstudiante', on_delete=django.db.models.deletion.CASCADE, to='appu.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Inscripción de Estudiante en Carrera',
                'verbose_name_plural': 'Inscripciones de Estudiantes en Carreras',
                'db_table': 'carreraestudiante',
                'unique_together': {('idcarrera', 'idestudiante')},
            },
        ),
        migrations.CreateModel(
            name='HorarioEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=15, verbose_name='Día')),
                ('horario_inicio', models.CharField(max_length=15, verbose_name='Hora de Inicio')),
                ('horario_fin', models.CharField(max_length=15, verbose_name='Hora de Fin')),
                ('idaula', models.ForeignKey(db_column='idAula', on_delete=django.db.models.deletion.CASCADE, to='appu.aula', verbose_name='Aula')),
                ('idestudiante', models.ForeignKey(db_column='idEstudiante', on_delete=django.db.models.deletion.CASCADE, to='appu.estudiante', verbose_name='Estudiante')),
                ('idmateria', models.ForeignKey(db_column='idMateria', on_delete=django.db.models.deletion.CASCADE, to='appu.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Horario de Estudiante',
                'verbose_name_plural': 'Horarios de Estudiantes',
                'db_table': 'horarioestudiante',
                'unique_together': {('idmateria', 'idestudiante', 'dia', 'horario_inicio', 'idaula')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota')),
                ('idestudiante', models.ForeignKey(db_column='idEstudiante', on_delete=django.db.models.deletion.CASCADE, to='appu.estudiante', verbose_name='Estudiante')),
                ('idmateria', models.ForeignKey(db_column='idMateria', on_delete=django.db.models.deletion.CASCADE, to='appu.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'nota',
                'unique_together': {('idmateria', 'idestudiante')},
            },
        ),
        migrations.CreateModel(
            name='MateriaProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmateria', models.ForeignKey(db_column='idMateria', on_delete=django.db.models.deletion.CASCADE, to='appu.materia', verbose_name='Materia')),
                ('idprofesor', models.ForeignKey(db_column='idProfesor', on_delete=django.db.models.deletion.CASCADE, to='appu.profesor', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Asignación de Materia a Profesor',
                'verbose_name_plural': 'Asignaciones de Materias a Profesores',
                'db_table': 'materiaprofesor',
                'unique_together': {('idprofesor', 'idmateria')},
            },
        ),
        migrations.CreateModel(
            name='HorarioProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=15, verbose_name='Día')),
                ('horario_inicio', models.CharField(max_length=15, verbose_name='Hora de Inicio')),
                ('horario_fin', models.CharField(max_length=15, verbose_name='Hora de Fin')),
                ('idaula', models.ForeignKey(db_column='idAula', on_delete=django.db.models.deletion.CASCADE, to='appu.aula', verbose_name='Aula')),
                ('idmateria', models.ForeignKey(db_column='idMateria', on_delete=django.db.models.deletion.CASCADE, to='appu.materia', verbose_name='Materia')),
                ('idprofesor', models.ForeignKey(db_column='idProfesor', on_delete=django.db.models.deletion.CASCADE, to='appu.profesor', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Horario de Profesor',
                'verbose_name_plural': 'Horarios de Profesores',
                'db_table': 'horarioprofesor',
                'unique_together': {('idprofesor', 'idmateria', 'dia', 'horario_inicio', 'idaula')},
            },
        ),
    ]
