# Generated by Django 5.2.1 on 2025-05-29 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carreraestudiante',
            table='carreraestudiante',
        ),
        migrations.AlterModelTable(
            name='horarioestudiante',
            table='horarioestudiante',
        ),
        migrations.AlterModelTable(
            name='horarioprofesor',
            table='horarioprofesor',
        ),
        migrations.AlterModelTable(
            name='materiaprofesor',
            table='materiaprofesor',
        ),
    ]
